// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using User.Models;

#nullable disable

namespace User.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("User.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Blog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventsUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Followers")
                        .HasColumnType("int");

                    b.Property<string>("FollowersUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Following")
                        .HasColumnType("int");

                    b.Property<string>("FollowingUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GistsUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GravatarId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Hireable")
                        .HasColumnType("bit");

                    b.Property<string>("HtmlUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NodeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationsUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublicGists")
                        .HasColumnType("int");

                    b.Property<int>("PublicRepos")
                        .HasColumnType("int");

                    b.Property<string>("ReceivedEventsUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReposUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SiteAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("StarredUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubscriptionsUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwitterUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
